# Stock market clustering

_Data Structures and Algorithms_

_Imperial College Business School_


---
This assignment is divided into three parts. In the first part, you will work on `pandas` data analysis. In the second part, you will implement a clustering algorithm to group companies based on their stock price movements. In the final part, you will explore ways to extend and improve this analysis. 

---

**The assignment is graded not only on correctness but also on the presentation of the results.** Try to make the results of your calculations easy to read with eg string formatting, do some plots if you find them useful, and comment your code.

**There are no OK tests to test your functions in this assignment.** It is intended to set you up working on a real problem where you have to explore data and the problem to figure out your approach. The first part will also require you to use a search engine to find the right pandas functions to use to analyse your data. Some potentially useful pandas functions are listed in the file `veryUseful.py`. 

**You're working as a group, so you may wish to divide the work into smaller pieces.** Some of you may want to start working on the Pandas part, and others on the algorithm part. There is a set of intermediary results available for testing your algorithm, so you can start immediately on both parts. See the details below in question 3.

**You may use generative AI (such as chatGPT) in the last part 3 of the assignment, but not in the other parts.** If you use generative AI (or other sources), please explain clearly how you have used it.

## Your group

You'll complete this assignment in your assigned study groups. If you are unsure about your group, please contact the programme team.

## Submission

Create a zip file containing your submission notebook (and possible other files required to run your code). Submit by uploading the zip file on the Hub: Go to DSA -> Assessment -> Homework 3. Only one submission is needed for your group. **Please note that the Hub has a file size limit.**

## Part 1: Pandas

**30% of grade**

In the previous homework, we used lists to study stock prices. The `pandas` library provides some more effective tools for data analysis.

The assignment comes with two files containing company data:
- `SP_500_firms.csv` with firm and ticker names
- `SP_500_close_2015.csv` with stock price data for 2015

Let's first load up this data.

In [1]:
# Load data into Python

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import warnings
warnings.filterwarnings ("ignore")

def read_names_into_dict():
    """
    Read company names into a dictionary
    """
    d = dict()
    with open("SP_500_firms.csv") as csvfile:
        input_file = csv.DictReader(csvfile)
        for row in input_file:
            #print(row)
            d[row['Symbol']] = [row['Name'],row['Sector']]
    return d

names_dict = read_names_into_dict()
comp_names = names_dict.keys()

# Read price data with pandas
filename = 'SP_500_close_2015.csv'
price_data = pd.read_csv(filename, index_col=0)

In [2]:
price_data

,MMM,ABT,ABBV,ACN,ATVI,AYI,ADBE,AAP,AES,AET,...,XEL,XRX,XLNX,XL,XYL,YHOO,YUM,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,156.678596,43.160459,61.986410,86.129228,19.765196,139.234407,72.339996,158.132353,12.860543,87.354435,...,33.927597,13.191375,41.513829,32.998169,37.072501,50.169998,69.542301,110.963875,27.853656,42.723658
2015-01-05,153.145069,43.170070,60.819874,84.674997,19.490271,135.889914,71.980003,156.047994,12.494440,86.173965,...,33.542483,12.903563,40.752108,33.199318,34.765202,49.130001,68.129346,115.103219,26.810004,42.467175
2015-01-06,151.511999,42.679830,60.518833,84.064223,19.126976,134.187800,70.529999,155.938290,12.212822,86.301853,...,33.720953,12.730876,40.161775,33.362155,34.560759,49.209999,67.293113,114.127520,25.786046,42.052863
2015-01-07,152.610267,43.025880,62.964797,85.828689,18.714587,136.566769,71.110001,159.289228,12.231597,88.033197,...,34.012134,12.893969,40.180818,33.381309,34.833350,48.590000,69.523080,116.965922,26.032190,42.920947
2015-01-08,156.267949,43.910238,63.623323,87.137495,18.901144,141.344618,72.919998,160.685446,12.419342,90.885990,...,34.406643,13.248937,41.075840,33.927287,35.096207,50.230000,70.734178,118.207726,26.396482,43.581878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-24,148.189203,44.272341,56.803111,103.227707,38.605835,239.688297,94.300003,148.953695,9.290114,108.882926,...,34.870979,10.636072,46.878702,38.910551,36.670848,34.110001,72.708631,102.048397,27.560025,47.824658
2015-12-28,148.218606,44.203626,57.084893,103.079148,38.714948,239.169142,94.199997,150.372014,9.173745,108.207559,...,35.261251,10.411228,46.829718,38.930084,36.542246,33.599998,72.551420,101.393919,27.421133,47.596117
2015-12-29,149.855459,44.979129,57.765054,104.307222,39.260511,236.393678,95.330002,152.020057,9.319206,109.458975,...,35.339308,10.529314,47.202005,39.467252,36.700524,34.040001,72.944441,102.129305,27.589787,48.023390
2015-12-30,148.894914,44.439223,58.105133,104.842030,39.111721,235.545059,95.279999,151.221000,9.212535,108.187699,...,35.514931,10.548996,46.868907,38.891017,36.473001,33.369999,72.521945,101.831180,27.252479,47.953830
2015-12-31,147.650116,44.085829,57.561007,103.495108,38.397531,233.418545,93.940002,150.332053,9.280416,107.383221,...,35.036844,10.460431,46.016568,38.265948,36.106986,33.259998,71.775213,101.950427,27.083825,47.615987

### Question 1: Returns

In the previous homework, we calculated stock price _returns_ over a period of time. The return is defined as the percentage change, so the return between periods $t-1$ and $t$ for stock price $p$ would be

$$
x_t = \frac{p_t - p_{t-1}}{p_{t-1}}.
$$

Calculate the returns in `pandas` for all the stocks in `price_data`.

In [3]:
# Calculate company returns in this cell
price_data.sort_index(inplace=True)
prices_return =pd.DataFrame()
for idx,col in enumerate(price_data.columns):
    prices_return[col] = price_data[col] / price_data[col].shift(1) - 1

In [4]:
prices_return

,MMM,ABT,ABBV,ACN,ATVI,AYI,ADBE,AAP,AES,AET,...,XEL,XRX,XLNX,XL,XYL,YHOO,YUM,ZBH,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-01-05,-0.022553,0.000223,-0.018819,-0.016884,-0.013910,-0.024021,-0.004976,-0.013181,-0.028467,-0.013514,...,-0.011351,-0.021818,-0.018349,0.006096,-0.062237,-0.020729,-0.020318,0.037304,-0.037469,-0.006003
2015-01-06,-0.010664,-0.011356,-0.004950,-0.007213,-0.018640,-0.012526,-0.020145,-0.000703,-0.022539,0.001484,...,0.005321,-0.013383,-0.014486,0.004905,-0.005881,0.001628,-0.012274,-0.008477,-0.038193,-0.009756
2015-01-07,0.007249,0.008108,0.040417,0.020989,-0.021561,0.017729,0.008223,0.021489,0.001537,0.020061,...,0.008635,0.012811,0.000474,0.000574,0.007887,-0.012599,0.033138,0.024870,0.009546,0.020643
2015-01-08,0.023967,0.020554,0.010459,0.015249,0.009969,0.034985,0.025453,0.008765,0.015349,0.032406,...,0.011599,0.027530,0.022275,0.016356,0.007546,0.033752,0.017420,0.010617,0.013994,0.015399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-24,0.000198,0.000000,-0.002049,-0.001820,0.002060,-0.000250,-0.004224,0.000470,0.004193,-0.004088,...,-0.003068,0.005545,-0.000627,0.009630,-0.001616,-0.009869,-0.001619,0.001362,0.003975,0.003126
2015-12-28,0.000198,-0.001552,0.004961,-0.001439,0.002826,-0.002166,-0.001061,0.009522,-0.012526,-0.006203,...,0.011192,-0.021140,-0.001045,0.000502,-0.003507,-0.014952,-0.002162,-0.006413,-0.005040,-0.004779
2015-12-29,0.011044,0.017544,0.011915,0.011914,0.014092,-0.011605,0.011996,0.010960,0.015856,0.011565,...,0.002214,0.011342,0.007950,0.013798,0.004331,0.013095,0.005417,0.007253,0.006151,0.008977
2015-12-30,-0.006410,-0.012003,0.005887,0.005127,-0.003790,-0.003590,-0.000525,-0.005256,-0.011446,-0.011614,...,0.004970,0.001869,-0.007057,-0.014600,-0.006199,-0.019683,-0.005792,-0.002919,-0.012226,-0.001448
2015-12-31,-0.008360,-0.007952,-0.009365,-0.012847,-0.018260,-0.009028,-0.014064,-0.005878,0.007368,-0.007436,...,-0.013462,-0.008396,-0.018186,-0.016072,-0.010035,-0.003296,-0.010297,0.001171,-0.006189,-0.007045

### Question 1.1: Highest and lowest daily returns

Use pandas to find the 10 highest daily returns amongst all companies. Search online for what were the reasons behind the highest returns. Present your results in a clean and immediately readable form.

Repeat with the lowest daily returns.

In [5]:
prices_return = prices_return.reset_index()

In [6]:
melt_data = pd.melt(prices_return,id_vars='Date',value_vars=prices_return.columns.tolist()[1:],value_name='return',var_name='stock_name')

In [7]:
# Highest Daily Return
print('Top 10 Highest Daily Return')
melt_data.sort_values('return',ascending=False)[:10]

Top 10 Highest Daily Return

              Date stock_name    return
49556   2015-08-27        FCX  0.286616
121581  2015-06-22        WMB  0.258999
111329  2015-10-14       TRIP  0.255361
53946   2015-01-29        HAR  0.237600
92698   2015-11-06       QRVO  0.232254
122409  2015-10-02       WYNN  0.228389
111160  2015-02-12       TRIP  0.224915
57809   2015-05-29        HUM  0.203128
64714   2015-10-21       KLAC  0.187895
86753   2015-04-08       PRGO  0.183899

In [8]:
# Lowest Daily Return
print('Top 10 Lowest Daily Return')
melt_data.sort_values('return',ascending=True)[:10]

Top 10 Lowest Daily Return

              Date stock_name    return
93187   2015-10-16        PWR -0.285006
74439   2015-05-27       KORS -0.241954
17528   2015-07-24       BIIB -0.220802
103776  2015-10-23       SRCL -0.192767
124176  2015-10-07        YUM -0.188324
88978   2015-02-04         RL -0.182169
74965   2015-06-26         MU -0.181515
82637   2015-12-04        NRG -0.179581
70523   2015-11-09        MNK -0.169981
3735    2015-10-28       AKAM -0.167306

### Question 1.2: Highest and lowest yearly returns

Find the 10 highest yearly returns amongst all companies. Present your results in a clean and immediately readable form.

Repeat with the lowest yearly returns.

In [9]:
yearly_return = pd.DataFrame(price_data.iloc[-1] / price_data.iloc[0] - 1)
yearly_return.columns = ['yearly_return']

In [10]:
# Highest Yearly Return
print('Top 10 Yearly Daily Return')
yearly_return.sort_values('yearly_return',ascending=False)[:10]

Top 10 Yearly Daily Return

      yearly_return
NFLX       1.294549
AMZN       1.190750
ATVI       0.942684
AYI        0.676443
NVDA       0.664514
GPN        0.600933
HRL        0.559016
EXR        0.544469
VRSN       0.527540
RAI        0.497837

In [11]:
# Lowest Yearly Return
print('Top 10 Lowest Daily Return')
yearly_return.sort_values('yearly_return',ascending=True)[:10]

Top 10 Lowest Daily Return

      yearly_return
CHK       -0.769785
SWN       -0.738314
FCX       -0.703792
KMI       -0.632032
MU        -0.592518
NRG       -0.559234
RRC       -0.553864
MRO       -0.546383
MUR       -0.538541
WYNN      -0.516602

### Question 1.3: Highest and lowest volatilities

Find the 10 highest yearly volatilities (standard deviations) amongst all companies. Present your results in a clean and immediately readable form.

Repeat with the lowest volatilities.

In [12]:
prices_return = prices_return.set_index('Date')

In [16]:
# Your code here
melt_data = melt_data.dropna()
melt_data_std = melt_data.groupby(['stock_name'])['return'].std().reset_index()
melt_data_std.columns = ['stock_name','std']

In [17]:
# top 10 highest yearly volatilities
print('Top 10 highest yearly volatilities')
melt_data_std.sort_values('std',ascending=False)[:10]

Top 10 highest yearly volatilities

    stock_name       std
174        FCX  0.044071
88         CHK  0.042784
384        RIG  0.037553
417        SWN  0.035199
482       WYNN  0.034918
376       QRVO  0.033473
302        MNK  0.032573
477        WMB  0.032224
389        RRC  0.032172
321       NFLX  0.031975

In [18]:
# Top 10 lowest yearly volatilities
print('Top 10 lowest yearly volatilities')
melt_data_std.sort_values('std',ascending=True)[:10]

Top 10 lowest yearly volatilities

    stock_name       std
259         KO  0.009063
87         CHD  0.009599
24         AJG  0.009711
352        PEP  0.009713
93         CLX  0.009725
142        DVA  0.009882
422          T  0.009943
468         VZ  0.009949
390        RSG  0.009973
355         PG  0.010106

### Question 2: Correlations

Analysts often care about the _correlation_ of stock prices between firms. Correlation measures the statistical similarity between the two prices' movements. If the prices move very similarly, the correlation of their _returns_  is close to 1. If they tend to make exactly the opposite movements (ie one price moves up and the other one down), the correlation is close to -1. If there is no clear statistical relationship between the movements of two stock prices, the correlation in their returns is close to zero.

For a sample of stock price returns $x,y$ with observations for $n$ days, the correlation $r_{xy}$ between $x$ and $y$ can be calculated as:

$$
r_{xy} = \frac{\sum x_i y_i - n \bar{x}\bar{y}}{ns_x s_y} = {\frac {n\sum x_{i}y_{i}-\sum x_{i}\sum y_{i}}{{\sqrt {n\sum x_{i}^{2}-(\sum x_{i})^{2}}}~{\sqrt {n\sum y_{i}^{2}-(\sum y_{i})^{2}}}}}.
$$

Here $\bar{x}$ refers to the average value of $x$ over the $n$ observations, and $s_x$ to its standard deviation.

Based on time series of the stock returns we just computed, we can calculate a  correlation value for each pair of stocks, for example between MSFT (Microsoft) and AAPL (Apple). This gives us a measure of the similarity between the two stocks in this time period.

Calculate all correlations between companies. You can search online for a `pandas` or `numpy` function that does this directly.

In [19]:
# Your code here
correl = prices_return.corr()

In [20]:
correl

,MMM,ABT,ABBV,ACN,ATVI,AYI,ADBE,AAP,AES,AET,...,XEL,XRX,XLNX,XL,XYL,YHOO,YUM,ZBH,ZION,ZTS
MMM,1.000000,0.598666,0.322637,0.632059,0.418550,0.450897,0.468755,0.257132,0.335378,0.317374,...,0.409630,0.499817,0.507630,0.543733,0.623741,0.316706,0.356204,0.433634,0.486263,0.293897
ABT,0.598666,1.000000,0.483669,0.644081,0.434370,0.494315,0.585671,0.371080,0.450213,0.464380,...,0.453393,0.538242,0.507487,0.619810,0.567309,0.376226,0.388070,0.640907,0.512479,0.463925
ABBV,0.322637,0.483669,1.000000,0.318051,0.226868,0.269096,0.347337,0.292497,0.303990,0.419365,...,0.261256,0.291590,0.323337,0.267436,0.321926,0.307020,0.289728,0.508626,0.323670,0.406247
ACN,0.632059,0.644081,0.318051,1.000000,0.462545,0.481296,0.560759,0.303227,0.395830,0.401335,...,0.388994,0.531886,0.510191,0.563153,0.615349,0.431369,0.353528,0.461188,0.546654,0.414050
ATVI,0.418550,0.434370,0.226868,0.462545,1.000000,0.310464,0.482777,0.223484,0.198134,0.285121,...,0.295291,0.369757,0.398586,0.388827,0.397004,0.365900,0.330467,0.370687,0.346790,0.323141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YHOO,0.316706,0.376226,0.307020,0.431369,0.365900,0.330425,0.313944,0.236624,0.186997,0.396039,...,0.102182,0.256104,0.281075,0.393230,0.419622,1.000000,0.195440,0.395166,0.317464,0.320558
YUM,0.356204,0.388070,0.289728,0.353528,0.330467,0.231669,0.482704,0.336033,0.231697,0.332220,...,0.249471,0.234024,0.308590,0.329237,0.301383,0.195440,1.000000,0.300762,0.316432,0.244152
ZBH,0.433634,0.640907,0.508626,0.461188,0.370687,0.373915,0.409590,0.319560,0.335481,0.504068,...,0.324352,0.397568,0.366280,0.455777,0.417949,0.395166,0.300762,1.000000,0.406406,0.415177
ZION,0.486263,0.512479,0.323670,0.546654,0.346790,0.292112,0.445173,0.345233,0.332337,0.338972,...,0.110038,0.481049,0.361690,0.503104,0.578436,0.317464,0.316432,0.406406,1.000000,0.298130
ZTS,0.293897,0.463925,0.406247,0.414050,0.323141,0.306790,0.377815,0.240448,0.276756,0.481854,...,0.173025,0.324956,0.347312,0.340149,0.344462,0.320558,0.244152,0.415177,0.298130,1.000000

### Question 2.1

Next, analyse the correlations between the companies:
- Define functions to print out the $n$ top and bottom correlated companies for any given company. 
- Use your functions to study the following companies in the tech sector: Amazon, Microsoft, Facebook, Apple, and Google. Comment on the results. Which (possibly other) companies are they most closely related to in terms of highest correlations? Would you have expected the results you see?

In [21]:
# Your code here
def find_top_corr(target, prices_return, top_n=10, bottom_n = 10):
    '''
    target: target company name
    prices_return: stock return matrix
    top_n: the number of top related stock
    bottom_n: the number of bottom related stock
    '''
    
    corr_matrix = prices_return.corr()
    try:
        
        bottom_corr = corr_matrix[target].sort_values(ascending=True)[:bottom_n]
        top_corr = corr_matrix[target].sort_values(ascending=False)[1:top_n+1]
        
        bottom_corr_df = pd.DataFrame(bottom_corr).reset_index()
        bottom_corr_df.columns = ['stock_code','corr']
        bottom_corr_df['stock_name'] = bottom_corr_df['stock_code'].apply(lambda x: names_dict[x][0])
        
        top_corr_df = pd.DataFrame(top_corr).reset_index()
        top_corr_df.columns = ['stock_code','corr']
        top_corr_df['stock_name'] = top_corr_df['stock_code'].apply(lambda x: names_dict[x][0])
        
        print(f'Top {top_n} corr company of {target}')
        print(top_corr_df)
        print('-'*50)
        print(f'Bottom {bottom_n} corr company of {target}')
        print(bottom_corr_df)
        print('-'*50)
        print(f'{names_dict[top_corr.index[0]][0]}({top_corr.index[0]}) are the most closely related to {names_dict[target][0]} ({target})')
    except:
        print('please inter a correct stock code')

In [22]:
find_top_corr('MSFT', prices_return, top_n=10, bottom_n = 10)

Top 10 corr company of MSFT
  stock_code      corr                 stock_name
0        MMC  0.604549           Marsh & McLennan
1         PG  0.604204           Procter & Gamble
2         MA  0.590886            Mastercard Inc.
3        ADP  0.589445  Automatic Data Processing
4       SBUX  0.583705            Starbucks Corp.
5      BRK-B  0.583071         Berkshire Hathaway
6         CA  0.580201                   CA, Inc.
7        ACN  0.577228              Accenture plc
8        AMP  0.577016       Ameriprise Financial
9       FISV  0.576048                 Fiserv Inc
--------------------------------------------------
Bottom 10 corr company of MSFT
  stock_code      corr                 stock_name
0       SRCL  0.028887             Stericycle Inc
1        NRG  0.090761                 NRG Energy
2        RIG  0.113785                 Transocean
3        SWN  0.114787        Southwestern Energy
4       URBN  0.128788           Urban Outfitters
5        KSS  0.130144               Kohl's Corp.
6        RRC  0.135989      Range Resources Corp.
7       KORS  0.143060      Michael Kors Holdings
8        KMI  0.148986              Kinder Morgan
9         DO  0.151773  Diamond Offshore Drilling
--------------------------------------------------
Marsh & McLennan(MMC) are the most closely related to Microsoft Corp. (MSFT)

In [23]:
find_top_corr('AMZN', prices_return, top_n=10, bottom_n = 10)

Top 10 corr company of AMZN
  stock_code      corr            stock_name
0      GOOGL  0.585553  Alphabet Inc Class A
1       GOOG  0.584337  Alphabet Inc Class C
2       SBUX  0.571951       Starbucks Corp.
3          V  0.560704             Visa Inc.
4         MA  0.538708       Mastercard Inc.
5       JNPR  0.531443      Juniper Networks
6       MSFT  0.524403       Microsoft Corp.
7         FB  0.500222              Facebook
8       HSIC  0.479651          Henry Schein
9        IPG  0.471228     Interpublic Group
--------------------------------------------------
Bottom 10 corr company of AMZN
  stock_code      corr                 stock_name
0       SRCL  0.056451             Stericycle Inc
1        RIG  0.060162                 Transocean
2        SWN  0.082376        Southwestern Energy
3       TRIP  0.087684                TripAdvisor
4        WFM  0.090700         Whole Foods Market
5         DO  0.091286  Diamond Offshore Drilling
6         HP  0.106780          Helmerich & Payne
7       KLAC  0.106865           KLA-Tencor Corp.
8        KSS  0.107043               Kohl's Corp.
9        NRG  0.126722                 NRG Energy
--------------------------------------------------
Alphabet Inc Class A(GOOGL) are the most closely related to Amazon.com Inc (AMZN)

In [24]:
find_top_corr('FB', prices_return, top_n=10, bottom_n = 10)

Top 10 corr company of FB
  stock_code      corr                 stock_name
0       FISV  0.619667                 Fiserv Inc
1         MA  0.617659            Mastercard Inc.
2       SBUX  0.598190            Starbucks Corp.
3      GOOGL  0.586548       Alphabet Inc Class A
4        TSS  0.580214      Total System Services
5       GOOG  0.569256       Alphabet Inc Class C
6          V  0.559706                  Visa Inc.
7       PAYX  0.559205               Paychex Inc.
8        ADP  0.557133  Automatic Data Processing
9        HON  0.556113       Honeywell Int'l Inc.
--------------------------------------------------
Bottom 10 corr company of FB
  stock_code      corr                        stock_name
0        NEM -0.002832  Newmont Mining Corp. (Hldg. Co.)
1        RIG  0.013327                        Transocean
2        SWN  0.047667               Southwestern Energy
3         DO  0.054310         Diamond Offshore Drilling
4        CHK  0.058682                 Chesapeake Energy
5        RRC  0.059883             Range Resources Corp.
6         HP  0.062859                 Helmerich & Payne
7        NRG  0.064936                        NRG Energy
8        KMI  0.114758                     Kinder Morgan
9        NOV  0.126840       National Oilwell Varco Inc.
--------------------------------------------------
Fiserv Inc(FISV) are the most closely related to Facebook (FB)

In [25]:
find_top_corr('AAPL', prices_return, top_n=10, bottom_n = 10)

Top 10 corr company of AAPL
  stock_code      corr                stock_name
0        ITW  0.601265       Illinois Tool Works
1        NOC  0.589368    Northrop Grumman Corp.
2        HON  0.576730      Honeywell Int'l Inc.
3       FISV  0.573935                Fiserv Inc
4       SWKS  0.573350        Skyworks Solutions
5        COL  0.570694          Rockwell Collins
6        TEL  0.569454      TE Connectivity Ltd.
7         BA  0.563837            Boeing Company
8        ROK  0.560731  Rockwell Automation Inc.
9        WFC  0.558983               Wells Fargo
--------------------------------------------------
Bottom 10 corr company of AAPL
  stock_code      corr                        stock_name
0        RRC  0.112711             Range Resources Corp.
1        CMG  0.130501            Chipotle Mexican Grill
2        NEM  0.143713  Newmont Mining Corp. (Hldg. Co.)
3        RIG  0.144045                        Transocean
4        SWN  0.146811               Southwestern Energy
5        MYL  0.159546                        Mylan N.V.
6         DO  0.160479         Diamond Offshore Drilling
7         HP  0.165746                 Helmerich & Payne
8        NRG  0.166044                        NRG Energy
9        HCN  0.174600                    Welltower Inc.
--------------------------------------------------
Illinois Tool Works(ITW) are the most closely related to Apple Inc. (AAPL)

In [26]:
find_top_corr('GOOG', prices_return, top_n=10, bottom_n = 10)

Top 10 corr company of GOOG
  stock_code      corr            stock_name
0      GOOGL  0.989365  Alphabet Inc Class A
1       AMZN  0.584337        Amazon.com Inc
2         FB  0.569256              Facebook
3        PGR  0.547913     Progressive Corp.
4       MSFT  0.520563       Microsoft Corp.
5         MA  0.512357       Mastercard Inc.
6       SBUX  0.501990       Starbucks Corp.
7        HON  0.496112  Honeywell Int'l Inc.
8       HSIC  0.489696          Henry Schein
9       FISV  0.487890            Fiserv Inc
--------------------------------------------------
Bottom 10 corr company of GOOG
  stock_code      corr                        stock_name
0       SRCL  0.017149                    Stericycle Inc
1        RIG  0.023044                        Transocean
2         DO  0.053734         Diamond Offshore Drilling
3        RRC  0.056774             Range Resources Corp.
4       URBN  0.067461                  Urban Outfitters
5        SWN  0.068524               Southwestern Energy
6        NEM  0.096350  Newmont Mining Corp. (Hldg. Co.)
7        CHK  0.096618                 Chesapeake Energy
8        NRG  0.100762                        NRG Energy
9      DISCA  0.106437        Discovery Communications-A
--------------------------------------------------
Alphabet Inc Class A(GOOGL) are the most closely related to Alphabet Inc Class C (GOOG)

## Part 2:  Clustering

**30% of grade**

In this part of the assignment, you will develop a clustering algorithm to study the similarity of different stocks. 

The general purpose of clustering analysis is dividing a set of objects into groups that are somehow "similar" to each other. It is a widespread tool used for exploratory data analysis in diverse fields in both science and business. For example, in marketing analytics, cluster analysis is employed to group consumers into segments based on their characteristics or _features_, such as age, post code, purchase history, etc. These features are somehow aggregated to compare the similarity between consumers. Based on this similarity, a clustering algorithm then divides the consumers into segments.

We will apply this idea on stock market data to identify groups of stocks that perform similarly over time. There are many reasons for grouping stocks together, such as analysing trading strategies, risk management, or simply presenting stock market information. Publicly traded companies are often grouped together by simple features such as the industry they operate in (eg tech companies or pharma companies), but here we'll take a data-driven approach, grouping together stocks that perform similarly over time. 

Cluster analysis is an umbrella term for many different algorithmic approaches. Here you'll develop one that's based on the concept of `greedy` algorithm design, specified below. You'll also have the opportunity to explore other approaches using Python libraries.

What is a good measure for stocks "performing similarly" to use for clustering. Let's use the one we just calculated: correlations in their returns. How can we use this similarity information for clustering? We now have access to all correlations between stock returns in S&P 500. We can think of this as a _graph_ as follows. The _nodes_ of the graph are the stocks (eg MSFT and AAPL). The _edges_ between them are the correlations, which we have just calculated between each stock, where the value of the correlation is the edge weight. Notice that since we have the correlations between all companies, this is a _dense_ graph, where all possible edges exist.

We thus have a graph representing pairwise "similarity" scores in correlations, and we want to divide the graph into clusters. There are many possible ways to do this, but here we'll use a _greedy_ algorithm design. The algorithm is as follows:

1. Sort the edges in the graph by their weight (ie the correlation), pick a number $k$ for the number of iterations of the algorithm
2. Create single-node sets from each node in the graph
3. Repeat $k$ times:
	1. Pick the graph edge with the highest correlation
	2. Combine the two sets containing the source and the destination of the edge
	3. Repeat with the next-highest weight edge
4. Return the remaining sets after the $k$ iterations 

What does the algorithm do? It first initializes a graph with no connections, where each node is in a separate set. Then in the main loop, it runs through the $k$ highest-weighted edges, and adds connections at those edges. This leads to sets being combined (or "merged"). The result is "groups" of stocks determined by the highest correlations between the stock returns. These are your stock clusters.

For example, suppose that the toy graph below represents four stocks: A,B,C,D and their return correlations. Suppose we pick $k=2$ and run the algorithm. 

<img src="cluster0.png" alt="cluster0" style="width: 200px;"/>


The algorithm would begin by initializing four separate sets of one node each: {A}, {B}, {C}, {D}. It would then first connect C and D because of their correlation 0.95, resulting in just three sets: {A}, {B}, and {C,D}. Then it would connect A and B, resulting in two sets of two nodes each: {A,B}, and {C,D}. These would be our clusters for $k=2$.

### Question 3: Implementing the algorithm

Your task is to implement the clustering algorithm using the functions below. First, for convenience in implementing the algorithm, let's create a list of the correlations from the pandas data.

In [27]:
def create_correlation_list(correl):
    """
    Creates a list of correlations from a pandas dataframe of correlations
    
    Parameters:
        correl: pandas dataframe of correlations
    
    Returns:
        list of correlations containing tuples of form (correlation, ticker1, ticker2)
    """
    n_comp = len(correl.columns)
    comp_names = list(correl.columns)
    # Faster if we use a numpy matrix
    correl_mat = correl.to_numpy()
    L = [] # create list
    for i in range(n_comp):
        for j in range(i+1,n_comp):
            L.append((correl_mat[i,j],comp_names[i],comp_names[j]))
    return L

edges = create_correlation_list(correl)

In [28]:
edges

[(0.5986661640297384, 'MMM', 'ABT'),
 (0.32263699601940277, 'MMM', 'ABBV'),
 (0.6320593488560183, 'MMM', 'ACN'),
 (0.41855006701119996, 'MMM', 'ATVI'),
 (0.45089749571328575, 'MMM', 'AYI'),
 (0.46875484430451547, 'MMM', 'ADBE'),
 (0.257131652175443, 'MMM', 'AAP'),
 (0.3353779674122444, 'MMM', 'AES'),
 (0.3173737409967593, 'MMM', 'AET'),
 (0.5059306055816823, 'MMM', 'AMG'),
 (0.5882159588805631, 'MMM', 'AFL'),
 (0.6045798382700396, 'MMM', 'A'),
 (0.5368795108735449, 'MMM', 'APD'),
 (0.40613526445868814, 'MMM', 'AKAM'),
 (0.3607667644812503, 'MMM', 'ALK'),
 (0.3610806682021867, 'MMM', 'ALB'),
 (0.38911625142178924, 'MMM', 'AA'),
 (0.444914376271326, 'MMM', 'ALXN'),
 (0.5543897045420154, 'MMM', 'ALLE'),
 (0.32741812638916556, 'MMM', 'AGN'),
 (0.6484196171133484, 'MMM', 'ADS'),
 (0.4309746246030884, 'MMM', 'LNT'),
 (0.4769977700019387, 'MMM', 'ALL'),
 (0.39145086506612636, 'MMM', 'GOOGL'),
 (0.3895210062045968, 'MMM', 'GOOG'),
 (0.5944321271151196, 'MMM', 'MO'),
 (0.3452385683090388, 'MMM', 'AMZN'),
 (0.4255210310725722, 'MMM', 'AEE'),
 (0.30761035993518276, 'MMM', 'AAL'),
 (0.3661419332112075, 'MMM', 'AEP'),
 (0.4128422615231995, 'MMM', 'AXP'),
 (0.5116259372409034, 'MMM', 'AIG'),
 (0.47756876592774244, 'MMM', 'AMT'),
 (0.35772830398431676, 'MMM', 'AWK'),
 (0.6696861087649051, 'MMM', 'AMP'),
 (0.47100513054063503, 'MMM', 'ABC'),
 (0.6834693090273709, 'MMM', 'AME'),
 (0.5358070484346914, 'MMM', 'AMGN'),
 (0.6213684748954159, 'MMM', 'APH'),
 (0.32606057578825826, 'MMM', 'APC'),
 (0.5062777891775644, 'MMM', 'ADI'),
 (0.3480135825609828, 'MMM', 'ANTM'),
 (0.6063237639928142, 'MMM', 'AON'),
 (0.3007514961427808, 'MMM', 'APA'),
 (0.3902768888758371, 'MMM', 'AIV'),
 (0.5157280000348692, 'MMM', 'AAPL'),
 (0.45812319049174577, 'MMM', 'AMAT'),
 (0.49889096855878634, 'MMM', 'ADM'),
 (0.4954184122213861, 'MMM', 'AJG'),
 (0.508812788840655, 'MMM', 'AIZ'),
 (0.5327303608262473, 'MMM', 'T'),
 (0.40042382326123577, 'MMM', 'ADSK'),
 (0.6634501906479042, 'MMM', 'ADP'),
 (0.5262875508021846, 'MMM', 'AN'),
 (0.46305542361470853, 'MMM', 'AZO'),
 (0.4294387657124174, 'MMM', 'AVGO'),
 (0.42093711929291117, 'MMM', 'AVB'),
 (0.5851920191705838, 'MMM', 'AVY'),
 (0.32934684564626215, 'MMM', 'BHI'),
 (0.5242367494100122, 'MMM', 'BLL'),
 (0.5031099175835763, 'MMM', 'BAC'),
 (0.4715923728542666, 'MMM', 'BCR'),
 (0.38873467402742906, 'MMM', 'BAX'),
 (0.6232837440418378, 'MMM', 'BBT'),
 (0.5731703923216476, 'MMM', 'BDX'),
 (0.407228595017633, 'MMM', 'BBBY'),
 (0.6823704437091597, 'MMM', 'BRK-B'),
 (0.33377248338886634, 'MMM', 'BBY'),
 (0.269180135642071, 'MMM', 'BIIB'),
 (0.6097638940836605, 'MMM', 'BLK'),
 (0.4037221241522454, 'MMM', 'HRB'),
 (0.5877393218545816, 'MMM', 'BA'),
 (0.4924754194789822, 'MMM', 'BWA'),
 (0.5104391872005145, 'MMM', 'BXP'),
 (0.3944374548433878, 'MMM', 'BSX'),
 (0.41169858749955857, 'MMM', 'BMY'),
 (0.5590681773415077, 'MMM', 'BF-B'),
 (0.5168732151467004, 'MMM', 'CHRW'),
 (0.5719822515583531, 'MMM', 'CA'),
 (0.3151092627009067, 'MMM', 'COG'),
 (0.5467632523410263, 'MMM', 'CPB'),
 (0.42747995110114545, 'MMM', 'COF'),
 (0.5659830716744821, 'MMM', 'CAH'),
 (0.5010137256013708, 'MMM', 'KMX'),
 (0.4553468373342096, 'MMM', 'CCL'),
 (0.5335651247833623, 'MMM', 'CAT'),
 (0.48944485363883977, 'MMM', 'CBG'),
 (0.47507300221159793, 'MMM', 'CBS'),
 (0.4521736733544527, 'MMM', 'CELG'),
 (0.24232351072158068, 'MMM', 'CNC'),
 (0.4022500272783976, 'MMM', 'CNP'),
 (0.4001518026768531, 'MMM', 'CTL'),
 (0.41839921929410295, 'MMM', 'CERN'),
 (0.28117763711558247, 'MMM', 'CF'),
 (0.5198090092235368, 'MMM', 'SCHW'),
 (0.24183561506578172, 'MMM', 'CHK'),
 (0.4443411655333466, 'MMM', 'CVX'),
 (0.21939540563003446, 'MMM', 'CMG'),
 (0.6426961736355138, 'MMM', 'CB'),
 (0.6029385376954478, 'MMM', 'CHD'),
 (0.20910778225968243, 'MMM', 'CI'),
 (0.3351236053233514, 'MMM', 'XEC'),
 (0.6603367293434618, 'MMM', 'CINF'),
 (0.6307352017182813, 'MMM', 'CTAS'),
 (0.5601525180383111, 'MMM', 'CSCO'),
 (0.5648697198489073, 'MMM', 'C'),
 (0.41995961119714265, 'MMM', 'CFG'),
 (0.4126587494049965, 'MMM', 'CTXS'),
 (0.5159151577281744, 'MMM', 'CME'),
 (0.4201603951736649, 'MMM', 'CMS'),
 (0.3725858897757238, 'MMM', 'COH'),
 (0.5772424743157633, 'MMM', 'CTSH'),
 (0.6120971473312963, 'MMM', 'CL'),
 (0.5325481290271146, 'MMM', 'CMCSA'),
 (0.4808378167242143, 'MMM', 'CMA'),
 (0.41638998405634214, 'MMM', 'CAG'),
 (0.27944202452370503, 'MMM', 'CXO'),
 (0.4135680818943567, 'MMM', 'COP'),
 (0.3648028581500059, 'MMM', 'ED'),
 (0.5075697716500145, 'MMM', 'STZ'),
 (0.5469506119207448, 'MMM', 'GLW'),
 (0.5467470378675925, 'MMM', 'COST'),
 (0.47320503630556465, 'MMM', 'CCI'),
 (0.43935725633026407, 'MMM', 'CSX'),
 (0.49142959739521164, 'MMM', 'CMI'),
 (0.5980535532053916, 'MMM', 'CVS'),
 (0.42814324882510224, 'MMM', 'DHI'),
 (0.7256540500436318, 'MMM', 'DHR'),
 (0.3211036381686417, 'MMM', 'DRI'),
 (0.4150487930332528, 'MMM', 'DVA'),
 (0.5189459781520063, 'MMM', 'DE'),
 (0.5400656095127664, 'MMM', 'DLPH'),
 (0.3936641355201652, 'MMM', 'DAL'),
 (0.5883263154503572, 'MMM', 'XRAY'),
 (0.31180268447858334, 'MMM', 'DVN'),
 (0.23252263256573064, 'MMM', 'DO'),
 (0.4131050287675602, 'MMM', 'DLR'),
 (0.5071151267068436, 'MMM', 'DFS'),
 (0.34157183582555345, 'MMM', 'DISCA'),
 (0.35125762417857004, 'MMM', 'DISCK'),
 (0.3373259112562751, 'MMM', 'DG'),
 (0.3562375482786397, 'MMM', 'DLTR'),
 (0.4179013909971979, 'MMM', 'D'),
 (0.521467681393552, 'MMM', 'DOV'),
 (0.5375792483550159, 'MMM', 'DOW'),
 (0.6002214769565677, 'MMM', 'DPS'),
 (0.39169029273504846, 'MMM', 'DTE'),
 (0.4376742539856048, 'MMM', 'DD'),
 (0.4041575848096887, 'MMM', 'DUK'),
 (0.588095046862037, 'MMM', 'DNB'),
 (0.47701041746622597, 'MMM', 'ETFC'),
 (0.4991463476709011, 'MMM', 'EMN'),
 (0.6323368051933254, 'MMM', 'ETN'),
 (0.4568759992345648, 'MMM', 'EBAY'),
 (0.5606791959212216, 'MMM', 'ECL'),
 (0.38376456501321965, 'MMM', 'EIX'),
 (0.4399213823949816, 'MMM', 'EW'),
 (0.41300148259454506, 'MMM', 'EA'),
 (0.45027155743371444, 'MMM', 'EMC'),
 (0.5899490443160978, 'MMM', 'EMR'),
 (0.21733116289786594, 'MMM', 'ENDP'),
 (0.3826051059100015, 'MMM', 'ETR'),
 (0.38391120816874674, 'MMM', 'EOG'),
 (0.19589690035379584, 'MMM', 'EQT'),
 (0.4817951498597428, 'MMM', 'EFX'),
 (0.472575064359382, 'MMM', 'EQIX'),
 (0.46010668194205, 'MMM', 'EQR'),
 (0.44121369540267974, 'MMM', 'ESS'),
 (0.471326256252332, 'MMM', 'EL'),
 (0.3769148518711511, 'MMM', 'ES'),
 (0.4105256029794701, 'MMM', 'EXC'),
 (0.31537470609807583, 'MMM', 'EXPE'),
 (0.6050284507029848, 'MMM', 'EXPD'),
 (0.4041310441694999, 'MMM', 'ESRX'),
 (0.4131106428930029, 'MMM', 'EXR'),
 (0.4885482856605194, 'MMM', 'XOM'),
 (0.26654588911266763, 'MMM', 'FFIV'),
 (0.4907419170949818, 'MMM', 'FB'),
 (0.5798915917830468, 'MMM', 'FAST'),
 (0.4747496445709537, 'MMM', 'FRT'),
 (0.6061846436704978, 'MMM', 'FDX'),
 (0.5315487746329903, 'MMM', 'FIS'),
 (0.5316471242957274, 'MMM', 'FITB'),
 (0.32888431918936906, 'MMM', 'FSLR'),
 (0.42943650574356423, 'MMM', 'FE'),
 (0.6655458751315768, 'MMM', 'FISV'),
 (0.47413305506893144, 'MMM', 'FLIR'),
 (0.5123281827927528, 'MMM', 'FLS'),
 (0.4647403880154526, 'MMM', 'FLR'),
 (0.39140718238946737, 'MMM', 'FMC'),
 (0.31863101962864593, 'MMM', 'FTI'),
 (0.3624765993015809, 'MMM', 'FL'),
 (0.504608785708848, 'MMM', 'F'),
 (0.45807638390615524, 'MMM', 'FBHS'),
 (0.6406713346396348, 'MMM', 'BEN'),
 (0.3580091002981169, 'MMM', 'FCX'),
 (0.3408186021985314, 'MMM', 'FTR'),
 (0.29888022982471957, 'MMM', 'GPS'),
 (0.35774598878740377, 'MMM', 'GRMN'),
 (0.6822370390770217, 'MMM', 'GD'),
 (0.56825272220358, 'MMM', 'GE'),
 (0.4704006570588921, 'MMM', 'GGP'),
 (0.595586731641656, 'MMM', 'GIS'),
 (0.46536205769706684, 'MMM', 'GM'),
 (0.6509079299643028, 'MMM', 'GPC'),
 (0.45914961344302924, 'MMM', 'GILD'),
 (0.46092435748909455, 'MMM', 'GPN'),
 (0.5787033350641375, 'MMM', 'GS'),
 (0.4464290531302941, 'MMM', 'GT'),
 (0.5475059558127198, 'MMM', 'GWW'),
 (0.3326391510989588, 'MMM', 'HAL'),
 (0.3929377133313197, 'MMM', 'HBI'),
 (0.38718837898490094, 'MMM', 'HOG'),
 (0.4160496304512282, 'MMM', 'HAR'),
 (0.4812004882559101, 'MMM', 'HRS'),
 (0.5305702358199175, 'MMM', 'HIG'),
 (0.4062005940589758, 'MMM', 'HAS'),
 (0.23726214116799846, 'MMM', 'HCA'),
 (0.35540178858483573, 'MMM', 'HCP'),
 (0.24163439292552952, 'MMM', 'HP'),
 (0.6401466096832291, 'MMM', 'HSIC'),
 (0.3263106528502668, 'MMM', 'HES'),
 (0.33480284019176076, 'MMM', 'HOLX'),
 (0.5927779519269085, 'MMM', 'HD'),
 (0.7274631210408, 'MMM', 'HON'),
 (0.535799055302247, 'MMM', 'HRL'),
 (0.4775399298824662, 'MMM', 'HST'),
 (0.4097456393747919, 'MMM', 'HPQ'),
 (0.1682771698090482, 'MMM', 'HUM'),
 (0.5499338775688396, 'MMM', 'HBAN'),
 (0.7684814551146741, 'MMM', 'ITW'),
 (0.22963449885345122, 'MMM', 'ILMN'),
 (0.5733669077333622, 'MMM', 'IR'),
 (0.4889349411505001, 'MMM', 'INTC'),
 (0.5023681371668112, 'MMM', 'ICE'),
 (0.5451325816060986, 'MMM', 'IBM'),
 (0.5250533602033323, 'MMM', 'IP'),
 (0.6145059987670316, 'MMM', 'IPG'),
 (0.5625686913153245, 'MMM', 'IFF'),
 (0.4636259281566187, 'MMM', 'INTU'),
 (0.37681396055118405, 'MMM', 'ISRG'),
 (0.5929752938706234, 'MMM', 'IVZ'),
 (0.3765956346847405, 'MMM', 'IRM'),
 (0.5183076749671335, 'MMM', 'JBHT'),
 (0.4952353508680786, 'MMM', 'JEC'),
 (0.6349523318112756, 'MMM', 'JNJ'),
 (0.6111695157290918, 'MMM', 'JCI'),
 (0.6201252915628235, 'MMM', 'JPM'),
 (0.42105337110923813, 'MMM', 'JNPR'),
 (0.4455449066624553, 'MMM', 'KSU'),
 (0.5281554659194407, 'MMM', 'K'),
 (0.519488853429, 'MMM', 'KEY'),
 (0.5976087368602147, 'MMM', 'KMB'),
 (0.4730474177099799, 'MMM', 'KIM'),
 (0.17563929960277203, 'MMM', 'KMI'),
 (0.41217307058862634, 'MMM', 'KLAC'),
 (0.2951307569057483, 'MMM', 'KSS'),
 (0.4259452003641617, 'MMM', 'KR'),
 (0.4624817662804266, 'MMM', 'LB'),
 (0.5412898134075844, 'MMM', 'LLL'),
 (0.2709697549006241, 'MMM', 'LH'),
 (0.49128145126500544, 'MMM', 'LRCX'),
 (0.5464374543093011, 'MMM', 'LM'),
 (0.546544841446953, 'MMM', 'LEG'),
 (0.43063134123778873, 'MMM', 'LEN'),
 (0.4115422626471791, 'MMM', 'LUK'),
 (0.45565379741848383, 'MMM', 'LVLT'),
 (0.37901522888444567, 'MMM', 'LLY'),
 (0.6033346299858899, 'MMM', 'LNC'),
 (0.5648886077982974, 'MMM', 'LLTC'),
 (0.39743038668876446, 'MMM', 'LKQ'),
 (0.6836251956750099, 'MMM', 'LMT'),
 (0.5756614767880583, 'MMM', 'L'),
 (0.5436919719627359, 'MMM', 'LOW'),
 (0.45163685978256735, 'MMM', 'LYB'),
 (0.5646281415219604, 'MMM', 'MTB'),
 (0.3680918207908579, 'MMM', 'MAC'),
 (0.27344397824220623, 'MMM', 'M'),
 (0.23704547805860818, 'MMM', 'MNK'),
 (0.311001011990028, 'MMM', 'MRO'),
 (0.3847882922068567, 'MMM', 'MPC'),
 (0.5854364421280339, 'MMM', 'MAR'),
 (0.6516138660705685, 'MMM', 'MMC'),
 (0.43179372926013254, 'MMM', 'MLM'),
 (0.5119621929571634, 'MMM', 'MAS'),
 (0.6322419130962577, 'MMM', 'MA'),
 (0.35212279528670565, 'MMM', 'MAT'),
 (0.6321045336376181, 'MMM', 'MKC'),
 (0.6017547118569722, 'MMM', 'MCD'),
 (0.46044676044254024, 'MMM', 'MCK'),
 (0.4955813893292334, 'MMM', 'MJN'),
 (0.5730467687753629, 'MMM', 'MDT'),
 (0.554279905027862, 'MMM', 'MRK'),
 (0.5502537937144054, 'MMM', 'MET'),
 (0.18953958772905505, 'MMM', 'KORS'),
 (0.5454539493639917, 'MMM', 'MCHP'),
 (0.24438390356655768, 'MMM', 'MU'),
 (0.48450913339430735, 'MMM', 'MSFT'),
 (0.47253446866192805, 'MMM', 'MHK'),
 (0.31426138201978915, 'MMM', 'TAP'),
 (0.5101928216845838, 'MMM', 'MDLZ'),
 (0.4612743931382463, 'MMM', 'MON'),
 (0.2851560543247213, 'MMM', 'MNST'),
 (0.5146436048891474, 'MMM', 'MCO'),
 (0.5732441416938501, 'MMM', 'MS'),
 (0.43204955121350974, 'MMM', 'MSI'),
 (0.3490536601802144, 'MMM', 'MUR'),
 (0.21135827793510065, 'MMM', 'MYL'),
 (0.5343992656649535, 'MMM', 'NDAQ'),
 (0.2564126657711024, 'MMM', 'NOV'),
 (0.2899960665594061, 'MMM', 'NAVI'),
 (0.3990550934942332, 'MMM', 'NTAP'),
 (0.3010873475536124, 'MMM', 'NFLX'),
 (0.43867763273028093, 'MMM', 'NWL'),
 (0.29937053126826807, 'MMM', 'NFX'),
 (0.16183111943382408, 'MMM', 'NEM'),
 (0.4828149498137189, 'MMM', 'NWSA'),
 (0.45298749221197276, 'MMM', 'NWS'),
 (0.5318371854010486, 'MMM', 'NLSN'),
 (0.501346999889383, 'MMM', 'NKE'),
 (0.4393968087573549, 'MMM', 'NI'),
 (0.35269288081615463, 'MMM', 'NBL'),
 (0.35214411365247283, 'MMM', 'JWN'),
 (0.4172118833144141, 'MMM', 'NSC'),
 (0.5261333322655065, 'MMM', 'NTRS'),
 (0.6361760514795939, 'MMM', 'NOC'),
 (0.1707435348030046, 'MMM', 'NRG'),
 (0.4755580480769292, 'MMM', 'NUE'),
 (0.39634213319327394, 'MMM', 'NVDA'),
 (0.5060388992177512, 'MMM', 'ORLY'),
 (0.4016993022702832, 'MMM', 'OXY'),
 (0.6792597283044978, 'MMM', 'OMC'),
 (0.22951347268624814, 'MMM', 'OKE'),
 (0.5881048090812335, 'MMM', 'ORCL'),
 (0.5077314315403371, 'MMM', 'OI'),
 (0.6132608892340523, 'MMM', 'PCAR'),
 (0.5972913536663402, 'MMM', 'PH'),
 (0.5000926082481996, 'MMM', 'PDCO'),
 (0.6483012002103682, 'MMM', 'PAYX'),
 (0.5592473626755202, 'MMM', 'PNR'),
 (0.5678831999045375, 'MMM', 'PBCT'),
 (0.6361634921203148, 'MMM', 'PEP'),
 (0.5851629325284882, 'MMM', 'PKI'),
 (0.2595526356211009, 'MMM', 'PRGO'),
 (0.47773052577016084, 'MMM', 'PFE'),
 (0.3667450606972106, 'MMM', 'PCG'),
 (0.49875075661981566, 'MMM', 'PM'),
 (0.4914899252423761, 'MMM', 'PSX'),
 (0.36805860750604413, 'MMM', 'PNW'),
 (0.24946427907715366, 'MMM', 'PXD'),
 (0.4668312290112662, 'MMM', 'PBI'),
 (0.6201065992202561, 'MMM', 'PNC'),
 (0.31592850748272505, 'MMM', 'RL'),
 (0.6314577078088538, 'MMM', 'PPG'),
 (0.39059232046893466, 'MMM', 'PPL'),
 (0.5513449304394068, 'MMM', 'PX'),
 (0.39048585885118825, 'MMM', 'PCLN'),
 (0.6348184324536604, 'MMM', 'PFG'),
 (0.5839008386123746, 'MMM', 'PG'),
 (0.6427765493761823, 'MMM', 'PGR'),
 (0.5153415717214068, 'MMM', 'PLD'),
 (0.5490418580895617, 'MMM', 'PRU'),
 (0.4343433666541408, 'MMM', 'PEG'),
 (0.5353845526449621, 'MMM', 'PSA'),
 (0.39691158518618425, 'MMM', 'PHM'),
 (0.297155170279654, 'MMM', 'PVH'),
 (0.3198625434827644, 'MMM', 'QRVO'),
 (0.33252833766354967, 'MMM', 'QCOM'),
 (0.275570426723627, 'MMM', 'PWR'),
 (0.3830839550847478, 'MMM', 'DGX'),
 (0.1852515403518298, 'MMM', 'RRC'),
 (0.5194844178938934, 'MMM', 'RTN'),
 (0.34178527396627206, 'MMM', 'O'),
 (0.4630881659579804, 'MMM', 'RHT'),
 (0.3887513341966802, 'MMM', 'REGN'),
 (0.4847104421017913, 'MMM', 'RF'),
 (0.5311854197064513, 'MMM', 'RSG'),
 (0.4813245458812061, 'MMM', 'RAI'),
 (0.49363079026469026, 'MMM', 'RHI'),
 (0.6970982452110973, 'MMM', 'ROK'),
 (0.6480533221245439, 'MMM', 'COL'),
 (0.6792312171562391, 'MMM', 'ROP'),
 (0.42744778535207095, 'MMM', 'ROST'),
 (0.382773048333457, 'MMM', 'RCL'),
 (0.5119166396014789, 'MMM', 'R'),
 (0.49870081432023267, 'MMM', 'SPGI'),
 (0.4410092422178821, 'MMM', 'CRM'),
 (0.3957450985308316, 'MMM', 'SCG'),
 (0.3221498943293559, 'MMM', 'SLB'),
 (0.41894506833699874, 'MMM', 'SNI'),
 (0.36973227371839346, 'MMM', 'STX'),
 (0.5025278874830155, 'MMM', 'SEE'),
 (0.43523674132103013, 'MMM', 'SRE'),
 (0.5085795988682786, 'MMM', 'SHW'),
 (0.34597969435153414, 'MMM', 'SIG'),
 (0.43601864480551655, 'MMM', 'SPG'),
 (0.4479179827554639, 'MMM', 'SWKS'),
 (0.502773219643788, 'MMM', 'SLG'),
 (0.4363121828869684, 'MMM', 'SJM'),
 (0.6216011691277898, 'MMM', 'SNA'),
 (0.3794711926119839, 'MMM', 'SO'),
 (0.3710080912657436, 'MMM', 'LUV'),
 (0.18990827378966993, 'MMM', 'SWN'),
 (0.37960101475995245, 'MMM', 'SE'),
 (0.43379849311408525, 'MMM', 'STJ'),
 (0.6687773709438507, 'MMM', 'SWK'),
 (0.3381013324541098, 'MMM', 'SPLS'),
 (0.4987737670983912, 'MMM', 'SBUX'),
 (0.4395032689535087, 'MMM', 'HOT'),
 (0.586997613400121, 'MMM', 'STT'),
 (0.3709377752674366, 'MMM', 'SRCL'),
 (0.5711695258185067, 'MMM', 'SYK'),
 (0.5767785130926768, 'MMM', 'STI'),
 (0.4215473861138811, 'MMM', 'SYMC'),
 (0.2763630888085282, 'MMM', 'SYF'),
 (0.39100257008246336, 'MMM', 'SYY'),
 (0.6439806203441251, 'MMM', 'TROW'),
 (0.46386607805993596, 'MMM', 'TGT'),
 (0.6379760503055114, 'MMM', 'TEL'),
 (0.5044834042255435, 'MMM', 'TGNA'),
 (0.3327493309046712, 'MMM', 'TDC'),
 (0.3723408007502755, 'MMM', 'TSO'),
 (0.6109997897006415, 'MMM', 'TXN'),
 (0.6616592675505499, 'MMM', 'TXT'),
 (0.5309932336864606, 'MMM', 'BK'),
 (0.5283059744002693, 'MMM', 'CLX'),
 (0.5751258582552573, 'MMM', 'KO'),
 (0.515917573706179, 'MMM', 'HSY'),
 (0.3637694301472988, 'MMM', 'MOS'),
 (0.6307001390352939, 'MMM', 'TRV'),
 (0.4411204832758773, 'MMM', 'DIS'),
 (0.5643255140974266, 'MMM', 'TMO'),
 (0.3972822035925089, 'MMM', 'TIF'),
 (0.5041636758425931, 'MMM', 'TWX'),
 (0.47194198691991446, 'MMM', 'TJX'),
 (0.5767601526293195, 'MMM', 'TMK'),
 (0.5478526552529219, 'MMM', 'TSS'),
 (0.591095378535416, 'MMM', 'TSCO'),
 (0.4217422916622172, 'MMM', 'TDG'),
 (0.18292163978510095, 'MMM', 'RIG'),
 (0.2622778672022341, 'MMM', 'TRIP'),
 (0.47073818065334827, 'MMM', 'FOXA'),
 (0.4625389193884679, 'MMM', 'FOX'),
 (0.6111698346388873, 'MMM', 'TYC'),
 (0.3188948168641829, 'MMM', 'TSN'),
 (0.6019962215322977, 'MMM', 'USB'),
 (0.43045758542092577, 'MMM', 'UDR'),
 (0.39230454058173997, 'MMM', 'ULTA'),
 (0.3528775925768851, 'MMM', 'UA'),
 (0.6321680237161119, 'MMM', 'UNP'),
 (0.3044082174559225, 'MMM', 'UAL'),
 (0.44282265367104534, 'MMM', 'UNH'),
 (0.5923639473401617, 'MMM', 'UPS'),
 (0.48553276304351217, 'MMM', 'URI'),
 (0.6595304716535458, 'MMM', 'UTX'),
 (0.22289345612348055, 'MMM', 'UHS'),
 (0.5358106865335674, 'MMM', 'UNM'),
 (0.2099848172417314, 'MMM', 'URBN'),
 (0.4425930165069367, 'MMM', 'VFC'),
 (0.39567105696430127, 'MMM', 'VLO'),
 (0.5362392057893586, 'MMM', 'VAR'),
 (0.33544135219326215, 'MMM', 'VTR'),
 (0.5015215494495088, 'MMM', 'VRSN'),
 (0.3447829132611617, 'MMM', 'VRSK'),
 (0.595218988255022, 'MMM', 'VZ'),
 (0.379072129331154, 'MMM', 'VRTX'),
 (0.3853466705343234, 'MMM', 'VIAB'),
 (0.5233385007739212, 'MMM', 'V'),
 (0.5485646372866716, 'MMM', 'VNO'),
 (0.4936281796047611, 'MMM', 'VMC'),
 (0.48021492639814245, 'MMM', 'WMT'),
 (0.49423483980933325, 'MMM', 'WBA'),
 (0.4301389329741562, 'MMM', 'WM'),
 (0.6221018789942242, 'MMM', 'WAT'),
 (0.6198714876375285, 'MMM', 'WFC'),
 (0.31248442232108636, 'MMM', 'HCN'),
 (0.3279823889739778, 'MMM', 'WDC'),
 (0.49401887213563245, 'MMM', 'WU'),
 (0.5150516946087585, 'MMM', 'WY'),
 (0.44953906261387605, 'MMM', 'WHR'),
 (0.24724639103154888, 'MMM', 'WFM'),
 (0.2788394287766634, 'MMM', 'WMB'),
 (0.4076256665725913, 'MMM', 'WEC'),
 (0.5494673713028474, 'MMM', 'WYN'),
 (0.24998654310225607, 'MMM', 'WYNN'),
 (0.4096302886482404, 'MMM', 'XEL'),
 (0.4998168284888771, 'MMM', 'XRX'),
 (0.5076300543556435, 'MMM', 'XLNX'),
 (0.5437326824791585, 'MMM', 'XL'),
 (0.6237406754677363, 'MMM', 'XYL'),
 (0.3167060821038363, 'MMM', 'YHOO'),
 (0.3562041431337024, 'MMM', 'YUM'),
 (0.4336337600947945, 'MMM', 'ZBH'),
 (0.48626315561061145, 'MMM', 'ZION'),
 (0.2938973046791202, 'MMM', 'ZTS'),
 (0.48366885347180505, 'ABT', 'ABBV'),
 (0.6440805298975264, 'ABT', 'ACN'),
 (0.4343704544494073, 'ABT', 'ATVI'),
 (0.4943145963795731, 'ABT', 'AYI'),
 (0.5856712329512728, 'ABT', 'ADBE'),
 (0.37108024558899005, 'ABT', 'AAP'),
 (0.45021273439046094, 'ABT', 'AES'),
 (0.46438007342055826, 'ABT', 'AET'),
 (0.5980603275249335, 'ABT', 'AMG'),
 (0.6908690622889622, 'ABT', 'AFL'),
 (0.6739910127112739, 'ABT', 'A'),
 (0.599280262440493, 'ABT', 'APD'),
 (0.39323302365629464, 'ABT', 'AKAM'),
 (0.44588838781407286, 'ABT', 'ALK'),
 (0.3772830347222565, 'ABT', 'ALB'),
 (0.28925554184357943, 'ABT', 'AA'),
 (0.5543339933541415, 'ABT', 'ALXN'),
 (0.586078363060468, 'ABT', 'ALLE'),
 (0.5111749564564795, 'ABT', 'AGN'),
 (0.6047910041532283, 'ABT', 'ADS'),
 (0.4499580020930321, 'ABT', 'LNT'),
 (0.5540722626638259, 'ABT', 'ALL'),
 (0.4417979583196886, 'ABT', 'GOOGL'),
 (0.4296318968526119, 'ABT', 'GOOG'),
 (0.5459456707491505, 'ABT', 'MO'),
 (0.4382762354140768, 'ABT', 'AMZN'),
 (0.4401960997787136, 'ABT', 'AEE'),
 (0.3885678361725894, 'ABT', 'AAL'),
 (0.44765410989960425, 'ABT', 'AEP'),
 (0.43461594585800145, 'ABT', 'AXP'),
 (0.5993383139323698, 'ABT', 'AIG'),
 (0.5789639637026676, 'ABT', 'AMT'),
 (0.4138146170831237, 'ABT', 'AWK'),
 (0.6549884843144143, 'ABT', 'AMP'),
 (0.5024175697461691, 'ABT', 'ABC'),
 (0.6342470553152787, 'ABT', 'AME'),
 (0.6776230474574846, 'ABT', 'AMGN'),
 (0.6160968739118706, 'ABT', 'APH'),
 (0.38378018562336697, 'ABT', 'APC'),
 (0.44840733789822507, 'ABT', 'ADI'),
 (0.4163999290876455, 'ABT', 'ANTM'),

Next, let's turn to the algorithm itself. Consider the example above, repeated here.

<img src="cluster0.png" alt="cluster0" style="width: 200px;"/>


Suppose we pick $k=3$ and have sorted the edge list in step 1 of the algorithm. How should we represent the clusters in step 2? One great way is to use a dictionary where each _key_ is a node, and each _value_ is another node that this node "points to". A cluster is then a chain of these links, which we represent as a dictionary.

In step 2 of the algorithm, we start with four nodes that point to themselves, ie the dictionary `{'A':'A','B':'B','C':'C','D':'D'}`. When a node points to itself, it ends the chain. Here the clusters are thus just the nodes themselves, as in the figure below.

<img src="cluster1.png" alt="cluster1" style="width: 200px;"/>


Let's walk through the algorithm's next steps. We first look at the highest-weight edge, which is between C and D. These clusters will be combined. In terms of the dictionary, this means that one of them will not point to itself, but to the other one (here it does not matter which one). So we make the dictionary at `C` point to `D`. The dictionary becomes `{'A':'A','B':'B','C':'D','D':'D'}`.

<img src="cluster2.png" alt="cluster2" style="width: 200px;"/>


The next highest correlation is between A and B, so these clusters would be combined. The dictionary becomes `{'A':'B','B':'B','C':'D','D':'D'}`.

<img src="cluster3.png" alt="cluster3" style="width: 200px;"/>


The third highest correlation is between C and B. Let's think about combining these clusters using the dictionary we have. Looking up `B`, we get `B`: the node B is in the _bottom_ of the chain representing its cluster. But when we look up `C`, it points to `D`. Should we make `C` point to `B`? No - that would leave nothing  pointing at `D`, and `C` and `D` should remain connected! We could perhaps have `C` somehow point at both nodes, but that could become complicated, so we'll do the following instead. We'll follow the chain to the bottom. In the dictionary, we look up `C` and see that it points to `D`. We then look up `D` which points to itself, so `D` is the _bottom_ node. We then pick one of the bottom nodes `B` and `D`, and make it point to the other. We then have the dictionary `{'A':'B','B':'B','C':'D','D':'B'}`, and the corresponding clustering in the figure below.

<img src="cluster4.png" alt="cluster4" style="width: 200px;"/>


In other words, we'll keep track of clusters in a dictionary such that **each cluster has exactly one bottom node**. To do this, we need a mechanism for following a cluster to the bottom. You'll implement this in the function `find_bottom` below. The function takes as input a node and a dictionary, and runs through the "chain" in the dictionary until it finds a bottom node pointing to itself.

The other thing we'll need to do is combine clusters by connecting two nodes. This means taking the two nodes, finding the bottom node for each node's cluster, and making one point to the other. You'll implement this in the function `merge_clusters` below.

Finally, you'll need to set up the algorithm by sorting the correlations, and then looping through this merging $k$ times. You'll implement this in the function `cluster_correlations` below. This completes the algorithm.

But there is one more thing. If you only keep track of a dictionary like `{'A':'B','B':'B','C':'D','D':'B'}`, how do you actually find the clusters from the dictionary? A convenient way is to store some extra information: the "starting nodes" of each cluster to which no other node links. For example, above these "starting nodes" would include all nodes `A,B,C,D` in the beginning, but only `A` and `C` in the end. If we keep track of these, we can then write a function that starts from each such remaining "starting node", works through to the bottom, and creates the cluster along the way. You'll implement this in the function `construct_sets` below.

### Intermediary results

You can load a pre-computed set of results up to this point using the following commands.

In [29]:
# Load intermediary results from a "pickle" file
# You can use these with your algorithm below
import pickle
file_name = 'cluster_correlations'
with open(file_name, "rb") as f:
    correl = pickle.load(f)
    edges = pickle.load(f)

firms = list(correl.columns)
print(firms[:10])
edges[:10]

['MMM', 'ABT', 'ABBV', 'ACN', 'ATVI', 'AYI', 'ADBE', 'AAP', 'AES', 'AET']

[(0.598666164029738, 'MMM', 'ABT'),
 (0.32263699601940254, 'MMM', 'ABBV'),
 (0.6320593488560189, 'MMM', 'ACN'),
 (0.41855006701119907, 'MMM', 'ATVI'),
 (0.4508974957132859, 'MMM', 'AYI'),
 (0.4687548443045165, 'MMM', 'ADBE'),
 (0.25713165217544326, 'MMM', 'AAP'),
 (0.33537796741224424, 'MMM', 'AES'),
 (0.31737374099675925, 'MMM', 'AET'),
 (0.5059306055816828, 'MMM', 'AMG')]

### Clustering implementation

Complete the following functions to implement the clustering algorithm.

In [31]:
def find_bottom(node, next_nodes):
    """
    Find the "bottom" of a cluster starting from node in dictionary next_nodes

    Parameters:
        node: starting node
        next_nodes: dictionary of node connections

    Returns:
        the bottom node in the cluster
    """
    # Your code here
    while:
        if node == next_nodes[node]:
            return node
        else:
            values = next_nodes[node]
            node = values
            


def merge_sets(node1, node2, next_nodes, set_starters):
    """
    Merges the clusters containing node1, node2 using the connections dictionary next_nodes.
    Also removes any bottom node which is no longer a "starting node" from set_starters.

    Parameters:
        node1: first node the set of which will be merged
        node2: second node the set of which will be merged
        next_nodes: dictionary of node connections
        set_starters: set of nodes that "start" a cluster

    Returns:
        does this function need to return something?
    """
    # Your code here
    next_nodes[node1] = node2


def cluster_correlations(edge_list, firms, k=200):
    """
    A mystery clustering algorithm
     
    Parameters:
         edge_list - list of edges of the form (weight,source,destination)
         firms - list of firms (tickers)
         k - number of iterations of algorithm

    Returns:
         next_nodes - dictionary to store clusters as "pointers"
            - the dictionary keys are the nodes and the values are the node in the same cluster that the key node points to
         set_starters - set of nodes that no other node points to (this will be used to construct the sets below)

    Algorithm:
         1 sort edges by weight (highest correlation first)
         2 initialize next_nodes so that each node points to itself (single-node clusters)
         3 take highest correlation edge
            check if the source and destination are in the same cluster using find_bottom
            if not, merge the source and destination nodes' clusters using merge_sets
         4 if max iterations not reached, repeat 3 with next highest correlation
         (meanwhile also keep track of the "set starters" ie nodes that have nothing pointing to them for later use)
    """
    # Sort edges
    sorted_edges = _____
    # Initialize dictionary of pointers
    next_nodes = {node: node for node in firms}
    # Keep track of "starting nodes", ie nodes that no other node points to in next_nodes
    set_starters = {node for node in firms}

    # Loop k times
    for i in range(k):
        # Your algorithm here
        
    return set_starters, next_nodes

SyntaxError: invalid syntax (1647695948.py, line 13)

Once we've run the algorithm, we'll need to construct the clusters. You can use the function below to do so.

In [ ]:
def construct_sets(set_starters, next_nodes):
    """
    Constructs sets (clusters) from the next_nodes dictionary
    
    Parameters:
        set_starters: set of starting nodes 
        next_nodes: dictionary of connections
    
    Returns: 
        dictionary of sets (clusters):
            key - bottom node of set; value - set of all nodes in the cluster
    
    """
    # Initialise an empty dictionary 
    all_sets = dict()
    
    # Loop:
    # Start from each set starter node
    # Construct a "current set" with all nodes on the way to bottom node
    # If bottom node is already a key of all_sets, combine the "current set" with the one in all_sets,
    # Otherwise add "current set" to all_sets
    for s in set_starters:
        cur_set = set()
        cur_set.add(s)
        p = s
        while next_nodes[p] != p:
            p = next_nodes[p]
            cur_set.add(p)
            
        if p not in all_sets:
            all_sets[p] = cur_set
        else: 
            for item in cur_set:
                all_sets[p].add(item)
    return all_sets

all_clusters = construct_sets(set_starters,next_nodes)

### Question 3.2: analysing the results

After you have implemented the algorithm in Python, add cells below answering the following questions:
- Do some detective work: what is the algorithm that you've implemented called? In what other graph problem is it often used? How are the problems related? (Hint: the algorithm is mentioned on the Wikipedia page for greedy algorithms.)
- Run the algorithm and present the results formatted in a useful way. 
- Discuss the results for different values of $k$.  
- Do the resulting clusters "make sense"? (You may need to search online what the companies do.) Verify that the stocks in your clusters perform similarly by plotting the returns and the (normalised) stock prices for some of the clusters.
- You may use graphs etc. to present your results.

## Part 3: 

**40% of grade**

Depending on your interests, you may work on either subsection below, or both. You might go deeper into one question than another, but for an outstanding grade, you should have at least some discussion on both.

You may use generative AI such as chatGPT to help with this part of the assignment (but not the other parts).

### In-depth analysis

The project is _open_ in the sense that you can probably think of further interesting questions to look into based on returns, correlations, and clusters. This is not required but being creative and going further than the above questions will make your work stand out. You can explore one or several of the ideas below, or come up with questions of your own.

Depending on your interests, you might look at different things. For example, when researching the algorithm, you might be interested in its complexity, and how to improve your implementation's efficiency. On Wikipedia, you may find a couple of ways to drastically improve the algorithm speed, but are relatively small changes to your code.

If you're more interested in the financial applications of clustering, there are also opportunities to think about further steps. For example, some people claim that you can derive trading strategies based on clustering - that often one of the stocks in a cluster is a leader and the others follow that price. If this is true, you could track the price of the leader stock and then trade the other stocks in the cluster based on changes in the leader's price. Do you think this would make sense? Do you have an idea on how to identify a leader stock?

You might also want to repeat the analysis for different time periods. You would be able to do this by looking at the code for the second homework to figure out how to read data from Yahoo Finance using pandas, and going through the process for all companies in the csv file for another time period. Perhaps you could explore for example how correlations between companies have changed over time, or how clusters found by your algorithm change over time.

### Exploring other clustering methods

You've used just one approach to clustering, and arguably not the best one. Research clustering algorithms and libraries to apply them in Python. Discuss some other algorithms that could be used, and how they differ from the one you've implemented. Look at the Python library `scikit-learn`. How would you apply the clustering algorithms provided by the library to stock price data? Would you need to develop new metrics other than correlations? If you want to go even further,  try running some of these other clustering algorithms on your data, and report the results. Start from here: http://scikit-learn.org/stable/modules/clustering.html#clustering; you'll find a stock market example there too. For future reference, you may also find other interesting machine-learning tools for both stock market analysis or other analytics purposes.

### Question 4

Create cells below to add your extra part as code and narrative text explaining your idea and results.

## All done!

Create a zip file containing your submission and upload it on the Hub.